# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout  ️
        uses: actions/checkout@v4

      - name: Lock npm version
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0

      - name: Install
        run: npm run init

      - name: Build
        run: npm run docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
          with:
              BRANCH: gh-pages
              FOLDER: docs/.vuepress/dist
              ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}